src/stock-orderable-group/orderable-group.service.js
src/stock-orderable-group/orderable-group.service.spec.js

TICKET: https://openlmis.atlassian.net/browse/ANGOLASUP-516
I restored changes that were overwritten in previous release.

ANGOLASUP-516: restore 'Remove the No Batch Defined options'

---

src/report/_superset-report.scss

TICKET: https://openlmis.atlassian.net/browse/ANGOLASUP-711

ANGOLASUP-711: added style in css in iframe of superset report

---

src/openlmis-header/header.controller.js
src/openlmis-header/header.html
src/openlmis-login/login-controller.js
src/openlmis-login/login-form.html
src/report/_superset-report.scss

TICKET: https://openlmis.atlassian.net/browse/ANGOLASUP-686

ANGOLASUP-686: Visually distinguish between Test and Production Servers

---

src/openlmis-header/header.controller.js
src/openlmis-header/header.html
src/openlmis-login/login-controller.js
src/openlmis-login/login-form.html
src/report/_superset-report.scss

TICKET: https://openlmis.atlassian.net/browse/ANGOLASUP-686

ANGOLASUP-686: refactored variable name 'isTestDomain'

---

src/admin-lot-list/admin-lot-list.routes.js
src/admin-lot-list/lot-list.controller.js
src/admin-lot-list/lot-list.controller.spec.js
src/admin-lot-list/lot-list.html

Added filtering lots by lot code in administration panel

ANGOLASUP-715: Added filtering lots by lot code in administration panel

---

src/admin-facility-list/facility-list.controller.js
src/admin-facility-list/facility-list.html
src/admin-facility-list/messages_en.json
src/admin-facility-print/_facility-print.scss
src/admin-facility-print/admin-facility-print.module.js
src/admin-facility-print/admin-facility-print.routes.js
src/admin-facility-print/facility-print.controller.js
src/admin-facility-print/facility-print.html
src/admin-facility-print/messages_en.json
src/admin-facility-print/print-information.html
src/admin-orderable-list/messages_en.json
src/admin-orderable-list/orderable-list.controller.js
src/admin-orderable-list/orderable-list.html
src/admin-orderable-print/_orderable-print.scss
src/admin-orderable-print/admin-orderable-print.module.js
src/admin-orderable-print/admin-orderable-print.routes.js
src/admin-orderable-print/messages_en.json
src/admin-orderable-print/orderable-print.controller.js
src/admin-orderable-print/orderable-print.html
src/admin-orderable-print/print-information.html

TICKET: https://openlmis.atlassian.net/browse/AO-744

AO-744: Extend Admin Products and Facilities pages with print option

---

src/stock-add-products-modal/add-products-modal.controller.js
src/stock-add-products-modal/add-products-modal.controller.spec.js
src/stock-add-products-modal/add-products-modal.service.js
src/stock-edit-lot-modal/edit-lot-modal.controller.js
src/stock-edit-lot-modal/edit-lot-modal.controller.spec.js
src/stock-edit-lot-modal/edit-lot-modal.service.js
src/stock-physical-inventory-draft/physical-inventory-draft-cache.service.js
src/stock-physical-inventory-draft/physical-inventory-draft.controller.js
src/stock-physical-inventory-draft/physical-inventory-draft.controller.spec.js
src/stock-physical-inventory/physical-inventory.factory.js
src/stock-physical-inventory/physical-inventory.factory.spec.js

Added functionality for caching products added with a new lot code.
JIRA task link: https://openlmis.atlassian.net/browse/ANGOLASUP-825

ANGOLASUP-825: Fixed inventory saving functionality

---

src/report/messages_en.json
src/report/report-list.controller.js
src/report/report-list.html

Ticket: https://openlmis.atlassian.net/browse/ANGOLASUP-797

ANGOLASUP-797-2: Catalogue and organize reports

---

src/report/report-list.controller.js
src/stock-physical-inventory-draft/physical-inventory-draft.controller.js
src/stock-physical-inventory-draft/physical-inventory-draft.html

I also deleted console logs from different ticket because of today's release - production ui should not have any console logs

ANGOLASUP-806: Change default reasons to be positive only

---

src/stock-add-products-modal/add-products-modal.controller.spec.js
src/stock-orderable-group/orderable-group.service.js
src/stock-physical-inventory-draft/physical-inventory-draft-cache.service.js
src/stock-physical-inventory-draft/physical-inventory-draft.controller.js

https://openlmis.atlassian.net/browse/ANGOLASUP-825

ANGOLASUP-825-2 - submit new lots fix

---

config.json

Ticket: https://openlmis.atlassian.net/browse/ANGOLASUP-831

ANGOLASUP-831: enable requisitionless orders

---

src/stock-adjustment-creation/adjustment-creation.controller.js
src/stock-adjustment-creation/adjustment-creation.html
src/stock-adjustment-creation/messages_en.json

AO-804: Display product prices on Stock Issues, Adjustments and Receives page

---

src/order-view/order-view.controller.js
src/order-view/order-view.html
src/order/messages_en.json
src/order/order-status.factory.js
src/order/order-statuses.constant.js
src/proof-of-delivery-view/proof-of-delivery-view.controller.js
src/proof-of-delivery-view/proof-of-delivery-view.controller.spec.js

https://openlmis.atlassian.net/browse/AO-827

AO-827: "Creating" status name displaying incorrectly

---

src/stock-price-changes/messages_en.json
src/stock-price-changes/stock-price-changes.controller.js
src/stock-price-changes/stock-price-changes.html
src/stock-price-changes/stock-price-changes.routes.js
src/stock-product-price-changes/messages_en.json
src/stock-product-price-changes/stock-product-price-changes.controller.js
src/stock-product-price-changes/stock-product-price-changes.html
src/stock-product-price-changes/stock-product-price-changes.routes.js
src/stockmanagement/stockmanagement-rights.constant.js

https://openlmis.atlassian.net/browse/AO-805
https://openlmis.atlassian.net/browse/AO-807

AO-805-fix: fixed pagination, added column, fixed rights, qa fixes

---

src/admin-role-form/messages_en.json
src/openlmis-rights/report-rights.constant.js
src/report-embedded-add/messages_en.json
src/report-embedded-add/report-embedded-add.controller.js
src/report-embedded-add/report-embedded-add.html
src/report-embedded-add/report-embedded-add.module.js
src/report-embedded-add/report-embedded-add.routes.js
src/report-embedded/messages_en.json
src/report-embedded/report-embedded-view.controller.js
src/report-embedded/report-embedded-view.html
src/report-embedded/report-embedded-view.routes.js
src/report-embedded/report-embedded.controller.js
src/report-embedded/report-embedded.html
src/report-embedded/report-embedded.module.js
src/report-embedded/report-embedded.routes.js
src/report-embedded/report-embedded.service.js

https://openlmis.atlassian.net/browse/AO-836

AO-836: Functionality for embedded reports

---

src/stock-adjustment-creation/adjustment-creation.controller.js
src/stock-adjustment-creation/adjustment-creation.html

Jira link: https://openlmis.atlassian.net/browse/OAM-5

OAM-5: Lot code filter UI improvements

---

src/admin-orderable-add/admin-orderable-add.module.js
src/admin-orderable-add/messages_en.json
src/admin-orderable-add/orderable-add-ftaps-list.html
src/admin-orderable-add/orderable-add-ftaps-modal.routes.js
src/admin-orderable-add/orderable-add-programs-list.html
src/admin-orderable-add/orderable-add-programs-modal.routes.js
src/admin-orderable-add/orderable-ftap-add.html
src/admin-orderable-add/orderable-program-add.html
src/admin-orderable-edit/orderable-add-edit-ftaps.controller.js
src/admin-orderable-edit/orderable-add-edit-general.controller.js
src/admin-orderable-edit/orderable-add-edit-general.controller.spec.js
src/admin-orderable-edit/orderable-edit-ftaps-list.controller.js
src/admin-orderable-edit/orderable-edit-programs.controller.js
src/admin-orderable-program-edit/orderable-program-edit.controller.js

https://openlmis.atlassian.net/browse/OAM-4

OAM-4: Create an Orderable configuration wizard

---

src/admin-orderable-add/orderable-program-add.html
src/admin-orderable-edit/messages_en.json
src/admin-orderable-edit/orderable-add-edit-ftaps.controller.js
src/admin-orderable-edit/orderable-add-edit-general.controller.js
src/admin-orderable-edit/orderable-add-edit-general.controller.spec.js
src/admin-orderable-edit/orderable-form.html

https://openlmis.atlassian.net/browse/OAM-4

OAM-4: added required fields, error messages, fixed notifications

---

src/openlmis-table/openlmis-table-component/services/openlmis-table-service/openlmis-table.service.js
src/openlmis-table/openlmis-table-component/services/openlmis-table-sorting-service/openlmis-table-sorting.service.js
src/requisition-approval/requisition-approval-list.controller.js
src/requisition-approval/requisition-approval-list.controller.spec.js
src/requisition-approval/requisition-approval-list.html
src/requisition-approval/requisition-approval.module.js
src/requisition-approval/requisition-approval.routes.js

OAM-38 - Added missing table component requistion -> approve view

OAM-38 - Added missing table component requistion -> approve view

---

.github/workflows/sonar-analysis.yml
sonar-project.properties

[OAM-36](https://openlmis.atlassian.net/browse/OAM-36)
Changes:
- Create a GH workflow to scan angola-ui repository on push/PR.
[OAM-36]: https://openlmis.atlassian.net/browse/OAM-36?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OAM-36: add sonarcloud analysis

---

src/admin-orderable-list/admin-orderable-list.routes.js
src/openlmis-table/openlmis-table-component/services/openlmis-table-sorting-service/openlmis-table-sorting.service.js
src/order-fulfillment/order-fulfillment.routes.js
src/order-fulfillment/order-fulfillment.routes.spec.js
src/order-view/order-view.routes.js
src/requisition-approval/requisition-approval.routes.js
src/requisition-approval/requisition-approval.routes.spec.js

OAM-38: Removed default sorting by emergency in order to prevent UI problems. Now user just sorts using header click

OAM-38: Removed default sorting by emergency

---

src/common/_layout.mixins.scss
src/common/_layout.scss
src/openlmis-home-alerts-panel/_openlmis-home-alerts-panel.scss
src/openlmis-home-alerts-panel/messages_en.json
src/openlmis-home-alerts-panel/openlmis-home-alerts-panel.controller.js
src/openlmis-home-alerts-panel/openlmis-home-alerts-panel.html
src/openlmis-home-alerts-panel/openlmis-home-alerts-panel.service.js
src/openlmis-home/_home.scss
src/openlmis-home/home.html

Changed layout to more user friendly. Now messages are in dashboard-like structure

OAM-18: Apply layout improvements

---

src/order-view/_order-view.scss
src/order-view/messages_en.json
src/order-view/order-view.controller.js
src/react-components/inputs/numeric-input.jsx
src/react-components/table/input-cell.jsx
src/requisition-order-create/order-create-print.service.js
src/requisition-order-create/order-create-tab.jsx
src/requisition-order-create/order-create-table.jsx
src/requisition-order-create/order-create.constant.jsx
src/requisition-order-create/order-create.routes.js
src/requisition-order-create/order-create.scss

To the view order page i have added n action which redirects to read-only order summary with option to print the order
https://openlmis.atlassian.net/browse/OAM-84

OAM-84: add read-only view with print order action

---

src/react-components/modals/_modal.scss
src/react-components/modals/modal.jsx
src/react-components/tab-navigation/_tab-navigation.scss
src/react-components/tab-navigation/tab-navigation.jsx
src/react-components/table/editable-table.jsx
src/react-components/table/table.jsx
src/requisition-order-create/order-create-form.jsx
src/requisition-order-create/order-create-summary-modal.jsx
src/requisition-order-create/order-create-tab.jsx
src/requisition-order-create/order-create-table-helper-functions.jsx
src/requisition-order-create/order-create-table.jsx
src/requisition-order-create/order-create.constant.jsx
src/requisition-order-create/order-create.scss

Added:
- pagination
- summary  view
- error marks
https://openlmis.atlassian.net/jira/software/projects/OAM/boards/147?selectedIssue=OAM-73

OAM-73: Add summary view

---

src/requisition-order-create/order-create-page.jsx
src/requisition-order-create/order-create-table.jsx

- removed error marks from read-only view
- removed save buttons
- changed breadcrumb
https://openlmis.atlassian.net/jira/software/projects/OAM/boards/147?selectedIssue=OAM-84

OAM-84: Adjusted better the readonly view

---

src/requisition-order-create/order-create-tab.jsx
src/requisition-order-create/order-create-table-helper-functions.jsx
src/requisition-order-create/order-create-table.jsx
src/stock-card-summary/stock-card-summary-repository-impl.js

- create order page do not hang anymore when selecting many orders
https://openlmis.atlassian.net/jira/software/projects/OAM/boards/147?selectedIssue=OAM-73

OAM-73: Improved performence of the component

---

src/order-view/messages_en.json
src/order-view/order-view.controller.js
src/order-view/order-view.html
src/order-view/order-view.routes.js

Added Requisitionless orders filtering
https://openlmis.atlassian.net/jira/software/projects/OAM/boards/147?assignee=63f8b93b1223974bc04c48e2&selectedIssue=OAM-131

OAM-131: Requisitionless orders filtering

---

src/order-view/messages_en.json
src/order-view/order-requisition-status.constant.js
src/order-view/order-view.controller.js
src/order-view/order-view.controller.spec.js
src/order-view/order-view.html
src/order-view/order-view.routes.js

Implement dropdown which will allow to choose whether user wants to see orders with/without requisition.
RELATED TO [OAM-26](https://openlmis.atlassian.net/browse/OAM-26)
[OAM-26]: https://openlmis.atlassian.net/browse/OAM-26?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HOTFIX: Replace requisitionless checkbox with filter dropdown.

---

src/order-view/messages_en.json

Change the label name to "Order Type".

fix: change label name

---

src/order-view/order-view.controller.js

This is fixing the requisitionless filter. It was filtering the other way around.

hotfix: fix the requisitionless filter

---

src/organization-add/messages_en.json
src/organization-add/organization-add.controller.js
src/organization-add/organization-add.controller.spec.js
src/organization-add/organization-add.html
src/organization-add/organization-add.module.js
src/organization-add/organization-add.routes.js

[OAM-190](https://openlmis.atlassian.net/browse/OAM-190)
Changes:
- Configured organization's create form allowing user to provide necessary data for the creation of Valid Source / Valid Destination.
- Init of a VS and VD while creating organization.
[OAM-190]: https://openlmis.atlassian.net/browse/OAM-190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OAM-190: create valid source and destination when creating organization

---

src/admin-facility-view/facility-view.controller.js
src/admin-facility-view/facility-view.controller.spec.js
src/admin-user-form/admin-user-form.routes.js
src/admin-user-form/user-form.controller.js

- fixed ward adding test
- fixed home facility tests

OAM-45: fixed test issues

---

src/requisition-order-create/order-create-tab.jsx

Ticket: https://openlmis.atlassian.net/browse/OAM-198

OAM-198: Filtered out quarantined orderables

---

src/admin-template-add/admin-template-add.module.js
src/admin-template-add/template-add.controller.js
src/admin-template-configure-settings/admin-template-configure-settings.module.js
src/admin-template-configure-settings/template-facility-type.factory.js
src/admin-user-form/admin-user-form.routes.js
src/admin-user-form/admin-user-form.routes.spec.js

- hidden wards from home facility select
- hidden wards/services type from rq-template add and edit
**Ticket**: https://openlmis.atlassian.net/jira/software/projects/OAM/boards/147?selectedIssue=OAM-185

OAM-185: Add restrictions regarding wards and services

---

src/openlmis-home/_home.scss

[OAM-203](https://openlmis.atlassian.net/browse/OAM-203)
Ss:
Changes:
- Reduce the size of notifications section.
- "My facility data" is visible on the home page (no need to scroll).
[OAM-203]: https://openlmis.atlassian.net/browse/OAM-203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OAM-203: reduce the size of notification section

---

src/requisition-product-grid/messages_en.json
src/requisition-product-grid/product-grid-cell.directive.js
src/requisition-product-grid/product-grid-quarantined-explanation.html
src/requisition/line-item.js
src/requisition/messages_en.json

[OAM-208](https://openlmis.atlassian.net/browse/OAM-208)
Changes:
- Support both EN and PT languages.
[OAM-208]: https://openlmis.atlassian.net/browse/OAM-208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OAM-208: base on translations rather than plain text

---

src/requisition-order-create/order-create-form.jsx

[OAM-199](https://openlmis.atlassian.net/browse/OAM-199)
Changes:
- Ensure tab uniqueness.
[OAM-199]: https://openlmis.atlassian.net/browse/OAM-199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OAM-199: ensure tab uniqueness

---

src/admin-orderable-edit/admin-orderable-edit.module.js
src/admin-orderable-edit/admin-orderable-edit.routes.js
src/admin-orderable-edit/admin-orderable-edit.scss
src/admin-orderable-edit/messages_en.json
src/admin-orderable-edit/orderable-edit-unit-assignment.controller.js
src/admin-orderable-edit/orderable-edit-unit-assignment.html
src/admin-orderable-edit/orderable-edit.controller.js
src/stock-adjustment-creation/adjustment-creation.html

ticket: https://openlmis.atlassian.net/browse/OAM-212

OAM-212: Add unit assignment view

---

src/stock-adjustment-creation/adjustment-creation.controller.js
src/stock-adjustment-creation/adjustment-creation.html
src/stock-card-summary-list/messages_en.json
src/stock-card-summary-list/stock-card-summary-list.controller.js
src/stock-card-summary-list/stock-card-summary-list.html

ticket: https://openlmis.atlassian.net/browse/OAM-27

OAM-27: Adjusted all views to include units

---

src/openlmis-facility-program-select/facility-program-cache.service.js
src/openlmis-facility-program-select/facility-program-cache.service.spec.js
src/referencedata-facility/facility.factory.js
src/referencedata-facility/facility.factory.spec.js
src/referencedata-facility/facility.service.js
src/requisition-convert-to-order/convert-to-order.html
src/requisition-order-create/order-create-form.jsx

[OAM-183](https://openlmis.atlassian.net/browse/OAM-183)
Changes:
- Adjust dropdowns and remove facilities with type of ward/service.
[OAM-183]: https://openlmis.atlassian.net/browse/OAM-183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OAM-183: remove wards from dropdowns

---

src/stock-adjustment-creation/adjustment-creation.controller.js
src/stock-adjustment-creation/adjustment-creation.html

ticket: https://openlmis.atlassian.net/browse/OAM-187

OAM 187: fix vaild sources for wards

---

src/stock-adjustment-creation/adjustment-creation.controller.js

comment in ticket: https://openlmis.atlassian.net/browse/OAM-187?focusedCommentId=92696

OAM-187: valid dest fixed

---

src/stock-adjustment-creation/adjustment-creation.html

Unit field for stock events has to be passed

Set unit field as required

---

src/admin-facility-add/facility-add.controller.js

- Creating geoZone during facility creation was added on BE in this ticket: https://openlmis.atlassian.net/browse/OAM-220

OAM-220: removed creating geoZone from FE

---

src/stock-adjustment-creation/adjustment-creation.controller.js
src/stock-adjustment-creation/adjustment-creation.controller.spec.js
src/stock-orderable-group/orderable-group-data-builder.spec.js
src/stock-orderable-group/orderable-group.service.js
src/stock-orderable-group/orderable-group.service.spec.js

- Adjusted stock on hand to the chosen unit
ticket: https://openlmis.atlassian.net/browse/OAM-224

OAM-224: fixed issue and receive

---

src/react-components/tab-navigation/tab-navigation.jsx
src/requisition-order-create/messages_en.json
src/requisition-order-create/order-create-form.jsx
src/requisition-order-create/order-create-table.jsx
src/requisition-order-create/order-create.constant.jsx
src/requisition-order-create/order-create.service.js

[OAM-201](https://openlmis.atlassian.net/browse/OAM-201)
Changes:
- Add deleting orders (only with status CREATING).
NOTE: Translations will be updated later.
[OAM-201]: https://openlmis.atlassian.net/browse/OAM-201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OAM-201: add deleting orders

---

src/requisition-order-create/messages_en.json
src/requisition-order-create/order-create-form.jsx

[OAM-226](https://openlmis.atlassian.net/browse/OAM-226)
Changes:
- Replace plain text with translations.
[OAM-226]: https://openlmis.atlassian.net/browse/OAM-226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OAM-226: add translations to react component

---

src/react-components/table/messages_en.json
src/react-components/table/table.jsx
src/requisition-order-create/messages_en.json
src/requisition-order-create/order-create-form.jsx
src/requisition-order-create/order-create-page.jsx
src/requisition-order-create/order-create-requisition-info.jsx
src/requisition-order-create/order-create-summary-modal.jsx
src/requisition-order-create/order-create-tab.jsx
src/requisition-order-create/order-create-table.jsx
src/requisition-order-create/order-create.constant.jsx
src/requisition-order-create/search-select.jsx
src/stock-card-summary-list/stock-card-summary-list.controller.js
src/stock-physical-inventory-draft/physical-inventory-draft.controller.js

Added missing translations to order create  component instead of plain text
https://openlmis.atlassian.net/browse/OAM-226?focusedCommentId=92843

OAM-226: Added missing translaitons to order create component

---

src/stock-adjustment-creation/adjustment-creation.controller.spec.js

fixed failing test after merging this: 
https://openlmis.atlassian.net/browse/OAM-229

OAM-229: Fixed test after changing validation

---

src/stock-card-summary-list/stock-card-summary-list.controller.js
src/stock-physical-inventory-draft/physical-inventory-draft.controller.js

resolving comment
https://openlmis.atlassian.net/browse/OAM-226?focusedCommentId=92906

OAM-226: Switched default display type to doses

---

src/openlmis-local-storage/local-storage.factory.js
src/referencedata-orderable-fulfills/orderable-fulfills.service.js
src/referencedata-program/program.service.js

Hotfix: Ensure that items in array are not undefined before putting them into local storage.

hotfix: unlock receive

---

src/stock-adjustment-creation/adjustment-creation.controller.js

fixing bug: https://openlmis.atlassian.net/browse/OAM-241

OAM-241: Added home facility as valid source for receive

---

src/openlmis-facility-program-select/openlmis-facility-program-select.component.js
src/openlmis-facility-program-select/openlmis-facility-program-select.controller.js
src/openlmis-facility-program-select/openlmis-facility-program-select.html
src/requisition-order-create/messages_en.json
src/requisition-order-create/order-create-summary-modal.jsx
src/stock-card-summary-list/stock-card-summary-list.html

Added missing translation in orderCreate (select empty msg)
Removed ward select in facility select where it was not needed

Bug: orderCreate and requisitinos create

---

src/referencedata-system-notification/system-notification.service.js
src/referencedata-system-notification/system-notification.service.spec.js

resolving: https://openlmis.atlassian.net/browse/OAM-249

OAM-249: removed caching notifications

---

src/openlmis-login/login-controller.js
src/openlmis-login/login-form.html
src/openlmis-main-state/header.controller.js
src/openlmis-main-state/header.html
src/openlmis-navigation/_navigation.scss

Task:
https://openlmis.atlassian.net/browse/AO-879
Changes:
Visually distinguish between Test and Production Servers

AO-879: Change colors for test environment

---

src/openlmis-unit-add/unit-of-orderable-cache.run.js
src/openlmis-unit-add/unit-of-orderable.service.js
src/referencedata-facility/facility.service.js

[OAM-263](https://openlmis.atlassian.net/browse/OAM-263)
Changes:
- Add caching for units.
- Add fetching (and caching) units on login.
- Add caching for getting facilities without wards.
[OAM-263]: https://openlmis.atlassian.net/browse/OAM-263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OAM-263: add caching for units and facilities without wards

---

src/stock-adjustment-creation/adjustment-creation.controller.js

Resolving ticket: https://openlmis.atlassian.net/browse/OAM-264

OAM-264: Fixed adjustments in offline mode

---

src/admin-facility-view/admin-facility-view.routes.js
src/admin-facility-view/ward-cache.run.js
src/admin-facility-view/ward.service.js
src/openlmis-facility-program-select/openlmis-facility-program-select.controller.js
src/stock-adjustment-creation/adjustment-creation.controller.js
src/stock-card-summary-list/stock-card-summary-list.controller.js
src/stock-card-summary-list/stock-card-summary-list.html
src/stock-receive-creation/receive-creation.routes.js

[OAM-263](https://openlmis.atlassian.net/browse/OAM-263)
Changes:
- Add caching for initial wards fetch.
- Adjust the SOH view in offline mode.
[OAM-263]: https://openlmis.atlassian.net/browse/OAM-263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OAM-263: add caching for wards, fix soh offline

---

src/requisition-view/requisition-view.controller.js

resolving ticket: https://openlmis.atlassian.net/browse/OAM-270

OAM-270: Changed print url in requisition module

---

src/stock-card-summary-list/stock-card-summary-list.html

[OAM-269](https://openlmis.atlassian.net/browse/OAM-269)
Changes:
- Disable print button if no facility / program (sync fetching with disabling).
[OAM-269]: https://openlmis.atlassian.net/browse/OAM-269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OAM-269: disable print button if no facility / program

---

src/stock-event/stock-event.factory.js
src/stock-physical-inventory-draft/physical-inventory-draft.controller.js
src/stock-physical-inventory/physical-inventory.factory.js

Resolving ticket: https://openlmis.atlassian.net/browse/OAM-277

OAM-277: added unitId to payload when sending physical inventory

---

src/referencedata-facilities-cache/referencedata-facilities-cache.run.js
src/referencedata-facilities-cache/referencedata-facilities-cache.run.spec.js
src/referencedata-facility/facility.service.js

[OAM-263](https://openlmis.atlassian.net/browse/OAM-263)
Changes:
- Add caching for getting facilities without wards.
- Add fetching facilities without wards on login.
[OAM-263]: https://openlmis.atlassian.net/browse/OAM-263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OAM-263: add caching for getting facilities without wards

---

src/react-components/modals/modal.jsx
src/referencedata-facilities-cache/referencedata-facilities-cache.run.spec.js
src/requisition-order-create/order-create-tab.jsx
src/requisition-order-create/order-create-table.jsx
src/requisition-view/requisition-view.controller.spec.js

resolving ticket: https://openlmis.atlassian.net/browse/OAM-287

OAM-287: fixed scroll on requisition order create page and failing tests

---

src/react-components/modals/modal.jsx
src/requisition-order-create/order-create-table.jsx

Finishing ticket: https://openlmis.atlassian.net/browse/OAM-287

OAM-287: displayed scroll after modal is closed

---

src/stock-adjustment-creation/adjustment-creation.controller.js

resolving ticket: https://openlmis.atlassian.net/browse/OAM-286

OAM-286: Fixed unpack view

---

src/stock-adjustment-creation/adjustment-creation.controller.js
src/stock-adjustment-creation/source-destination-cache.run.js
src/stock-adjustment-creation/source-destination.service.js
src/stock-valid-sources/source-cache.run.js
src/stock-valid-sources/source-cache.run.spec.js

Resolving ticket: https://openlmis.atlassian.net/browse/OAM-290

OAM-290: Made issue work offline

---

src/admin-orderable-edit/messages_en.json
src/admin-orderable-edit/orderable-edit-kit-unpack-list.controller.js
src/admin-orderable-edit/orderable-edit-kit-unpack-list.html
src/stock-adjustment-creation/adjustment-creation.controller.js
src/stock-adjustment-creation/adjustment-creation.controller.spec.js

ticket: https://openlmis.atlassian.net/browse/OAM-273

OAM-273: OpenLMIS kit unpack hangs during submission

---

src/stock-adjustment-creation/adjustment-creation.controller.js

https://openlmis.atlassian.net/browse/OAM-273

OAM-273: fix for counting quantity

---

src/openlmis-cached-repository/openlmis-cached-resource.js
src/referencedata-facility/facility.service.js
src/referencedata-facility/referencedata-facility.run.js

resolving comment: https://openlmis.atlassian.net/browse/OAM-254?focusedCommentId=94120

OMA-291: Removed destroy function

---

src/stock-adjustment-creation/adjustment-creation.controller.spec.js
src/stock-valid-sources/source-cache.run.js

resolving comment: https://openlmis.atlassian.net/browse/OAM-291?focusedCommentId=94140

OAM-291: added caching vs for wards

---

src/stock-adjustment-creation/adjustment-creation.controller.js

Resolving Bug from ticket: 
https://openlmis.atlassian.net/browse/ANGOLASUP-908

ANGOLASUP-908: fixed stock adjustments

---

src/shipment-view/shipment-view.controller.js

resolving comment: https://openlmis.atlassian.net/browse/ANGOLASUP-909?focusedCommentId=94476

ANGOLASUP-909: handled case when no stock is available

---

src/openlmis-facility-program-select/facility-program-cache.service.js
src/requisition-view-tab/_requisition-view-tab.scss
src/requisition-view-tab/messages_en.json
src/requisition-view-tab/requisition-view-tab.controller.js
src/requisition-view-tab/requisition-view-tab.html

resolving ticket: https://openlmis.atlassian.net/browse/ANGOLASUP-918

ANGOLASUP-918: product name filter added on requisition page

---

src/admin-supply-line-list/admin-supply-line-list.routes.js
src/admin-supply-line-list/admin-supply-line-list.routes.spec.js
src/admin-valid-destination-list/admin-valid-destination-list.routes.js
src/admin-valid-source-list/admin-valid-source-list.routes.js
src/openlmis-cached-repository/openlmis-cached-resource.js

Task: 
https://openlmis.atlassian.net/browse/ANGOLASUP-931
Changes:
- Saving the entire response to local database
- Retrieving facilities from cache on the valid source and destination list, supply line list

ANGOLASUP-931: Retrieving facilities from cache

---

src/stock-add-products-modal/add-products-modal.controller.js
src/stock-edit-lot-modal/edit-lot-modal.controller.js
src/stock-physical-inventory-draft/messages_en.json
src/stock-physical-inventory-draft/physical-inventory-draft-cache.service.js
src/stock-physical-inventory-draft/physical-inventory-draft.controller.js
src/stock-physical-inventory-draft/physical-inventory-draft.controller.spec.js
src/stock-physical-inventory/physical-inventory.service.js
src/stock-physical-inventory/physical-inventory.service.spec.js

Task:
https://openlmis.atlassian.net/browse/ANGOLASUP-936
Changes:
Improved saving and caching of the Physical Inventory draft

ANGOLASUP-936: Improved saving and caching of the Physical Inventory draft

---

src/stock-edit-lot-modal/edit-lot-modal.controller.js

resolving bug: https://openlmis.atlassian.net/browse/AO-901

AO-901: Enabled new lot edition in receive view

---

src/admin-user-list/user-list.controller.js
src/admin-user-list/user-list.routes.js

resolving bug: https://openlmis.atlassian.net/browse/AO-891

AO-891: Fixed sorting users list

---

src/common/_mixins.scss
src/openlmis-header/header.html
src/select-products-modal/select-products-modal.controller.js
src/select-products-modal/select-products-modal.html

resolved bugs:
https://openlmis.atlassian.net/browse/AO-893
https://openlmis.atlassian.net/browse/AO-896

AO-893 and AO-896: resolved tickets AO-893 and AO-896

---

src/admin-user-list/user-list.controller.spec.js

fixed faling build
http://3.208.180.34:8080/job/angola-ui/639/console

AO-899: user list test fix
